### ISSUE TITLE
Enhancing GPU support, adding VTT/SRT export, and updating to Whisper 2.0

### ISSUE THREAD

**Issue by RicardoAHS** [Kabanosk/website_for_whisper#13]
Hello,

I recently tried using your "website_for_whisper" repository and found it very helpful. I have a few suggestions and questions that I hope could improve the project:

GPU support: I noticed that the current implementation seems to be running the Whisper model on the CPU, which can be quite slow for some users. It would be great if the repository could be updated to support running the model on a GPU when available. This should improve the performance and make the transcription process faster.

VTT and SRT export: Another useful feature to add would be the ability to export the transcriptions in VTT and SRT formats. These formats are widely used for subtitles and captions, and having the option to export in these formats would be beneficial for many users.

Whisper 2.0: I saw that OpenAI has released Whisper 2.0, an updated version of the original Whisper model. I was wondering if the repository is using the latest version of the model. If not, could you please update the repository to use Whisper 2.0?

Thank you for your work on this project. I look forward to any updates and improvements you might make in the future.

**Comment by Kabanosk** [comment]
Hi! Thank you for the great overview of the project. I will improve my project when I have time. You can also improve something if you want 😁

**Comment by Kabanosk** [comment]
Hi! I had time today to make the SRT export. Can you check if it works @RicardoAHS ?

**Comment by RicardoAHS** [comment]
> Hi! I had time today to make the SRT export. Can you check if it works @RicardoAHS ?

Hello,

Thank you for implementing the SRT export feature! I tested it and while it works, I noticed that the audio-to-text conversion still takes a long time. Additionally, when trying to save the SRT file, the filename I entered in the "Enter the filename for subtitles - it will be saved as .srt file" field is not being used. Instead, the saved file has a different name. Furthermore, when I attempt to download the SRT file, an error occurs.

On a related note, I found a repository that helped me create two scripts, one for converting video and another for converting audio. These scripts perform the audio-to-text conversion much faster, but they're not adapted as web applications. Both scripts are written in Python and can be found in this repository:

https://github.com/jianfch/stable-ts

These scripts have been very useful for generating accurate subtitles. I think incorporating them into your project could help improve the performance of the audio-to-text conversion process. Here are the scripts:

Setup:

`pip install -U stable-ts`
`pip install moviepy`

Video script:

```
import os
import sys
from moviepy.editor import *
import stable_whisper

def video_to_audio(video_file):
    audio_file = os.path.splitext(video_file)[0] + '.mp3'
    video = VideoFileClip(video_file)
    audio = video.audio
    audio.write_audiofile(audio_file)
    return audio_file

def transcribe_and_create_srt(audio_file):
    srt_file = os.path.splitext(audio_file)[0] + '.srt'
    model = stable_whisper.load_model('base')
    result = model.transcribe(audio_file)
    result.to_srt_vtt(srt_file, word_level=False)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please provide the name of the video file as an argument.")
        sys.exit(1)

    video_file = sys.argv[1]
    if not os.path.isfile(video_file):
        print("The provided video file does not exist.")
        sys.exit(1)

    print("Extracting audio from the video file...")
    audio_file = video_to_audio(video_file)

    print("Transcribing and generating SRT file...")
    transcribe_and_create_srt(audio_file)

    print("Process completed successfully.")
```
`python video_to_srt.py "video_name.mp4"`
    
Audio script:

```
import os
import stable_whisper

def transcribe_and_create_srt(audio_file):
    srt_file = os.path.splitext(audio_file)[0] + '.srt'
    model = stable_whisper.load_model('base')
    result = model.transcribe(audio_file)
    result.to_srt_vtt(srt_file, word_level=False)

if __name__ == "__main__":
    audio_file = input("Enter the name of the audio file (with extension): ")
    if os.path.exists(audio_file):
        transcribe_and_create_srt(audio_file)
        print(f"The SRT file has been created: {os.path.splitext(audio_file)[0] + '.srt'}")
    else:
        print("The audio file is not located in the script folder.")
```
`python audio_to_srt.py`

- - - - -

I hope this feedback is helpful. I appreciate your efforts to improve this project and am looking forward to any further updates. Please note that I'm not a programmer, but I managed to generate both scripts using GPT-4.

**Comment by Kabanosk** [comment]
Thank you for very useful tips. I'm going to try to fix the error with the srt files right now.

Edit: @RicardoAHS Are you enter the filename before or after the conversion? And can you copy and paste the error message from terminal?

**Comment by Kabanosk** [comment]
> On a related note, I found a repository that helped me create two scripts, one for converting video and another for converting audio. These scripts perform the audio-to-text conversion much faster, but they're not adapted as web applications. Both scripts are written in Python and can be found in this repository:
> https://github.com/jianfch/stable-ts

I changed the code a bit to use this repository and it gives very good results. Can you see if it works? 
To do this, go to the `feature/subtitles-quality` branch and run the startup script (`python3 run.py` in the src directory)

**Comment by RicardoAHS** [comment]
@Kabanosk I followed your instructions and tested the project from the feature/subtitles-quality branch. I'm happy to report that it works much better now! Thank you so much for taking the time to improve the project.

**Comment by Kabanosk** [comment]
Thank you for your interest in the project. If you have other ideas to improve this project - write an issue. I will try to do it
