### ISSUE TITLE
Internal Server Issue when trying to transcribe a file

### ISSUE THREAD

**Issue by BigZhenjie** [Kabanosk/website_for_whisper#16]
**Describe the bug**
For some reason, I am getting an internal server error in the content of the output file when I try to transcribe a m4a file.
**OS (please complete the following information):**
 - [e.g. iOS]
 - windows

**Additional context**
This is the error msg: 
![image](https://github.com/Kabanosk/whisper-website/assets/81547949/536b2e03-f35f-43be-aaa3-dcf4539e02c9)

**Comment by Kabanosk** [comment]
Have you tried other file types?

**Comment by BigZhenjie** [comment]
Yes I tried mp3 (still doesn't work for me), but I just realized there could be another issue that is causing this. I followed the steps in your readme and when I run "python run.py", I get this warning msg: 
![image](https://github.com/Kabanosk/whisper-website/assets/81547949/bfda8399-b904-43e3-93f7-7eb7be482822)
Do you know if this might be the cause?

**Comment by BigZhenjie** [comment]
I have. I tried converting the m4a to mp3, but the converted mp3 file still reflects the same issue. This is the result file: 
![image](https://github.com/Kabanosk/whisper-website/assets/81547949/0d65276f-66cb-4039-a8e3-638c6881b4cc)

**Comment by HUYDGD** [comment]
wav file also get the same error

**Comment by Kabanosk** [comment]
Hi! I have updated some part of the code - can you check if the error still occurs? @HUYDGD @BigZhenjie
