### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MANJU-THAMPAN** [Kabanosk/website_for_whisper#19]
![Screenshot 2024-01-16 214416](https://github.com/Kabanosk/whisper-website/assets/141439870/f3e0925a-bb57-4723-9004-f4c046ae592a)

**Comment by Kabanosk** [comment]
Hi! I think that it might be problem with the access to `audio.mp3` file, but unfortunately I don't have Windows operating system, so I cannot help more with just a picture. If you say some things you tried to fix this error, I can try to help

**Comment by MANJU-THAMPAN** [comment]
The downloaded file shows internal server error

**Comment by MANJU-THAMPAN** [comment]
The issue is resolved,problem was with the ffmpeg.

**Comment by MANJU-THAMPAN** [comment]
The problem is resolved.The issue was related to ffmpeg
