### ISSUE TITLE
GUI Application?

### ISSUE THREAD

**Issue by kirill0ermakov** [Kabanosk/website_for_whisper#2]
Greetings, could you please tell me if there are plans to make a full-fledged GUI that you can run as a local program?

**Comment by Kabanosk** [comment]
Hi! Maybe in the future. Now you can run this website on localhost using uvicorn. I can make it easier to run if you want

**Comment by kirill0ermakov** [comment]
It's just that I, like many users who are not related to programming, not really like to use the terminal for work :)

**Comment by Kabanosk** [comment]
Okey, so you must install git, pip and python, then you go to terminal / command prompt and make all steps from the repo readme: 
1. Clone the repo - `git clone git@github.com:Kabanosk/website_for_whisper.git`
2. Go to src directory - `cd website_for_whisper/src`
3. Install requirements - `pip install -r ../reqirements.txt`
4. Run the `run.py` file - `python3 run.py`
5. Go to your browser and type `http://127.0.0.1:8000`

You have exact command you write to run the web app after ' - '

**Comment by Kabanosk** [comment]
Tell me if you will have any problem :D

**Comment by Kabanosk** [comment]
Hi @kirill0ermakov ! I don't have Windows or macOS system unfortunately. Can you test the `windows_run.bat` file if you have windows or `unix_run.sh` if you have macOS?

When you download the zip file, then in src folder is file `windows_run.bat`/`unix_run.sh`. Can you double click on it and tell me if you see the website?

It will look like this:
![2022-10-03_19-22](https://user-images.githubusercontent.com/56364007/193639845-aee5014d-54d2-4fb0-83fa-1f6213fe3a14.png)

**Comment by kirill0ermakov** [comment]
I try this on Windows, but this dont work, sorry.

**Comment by Kabanosk** [comment]
I am sorry that this don't work. When I will have access to windows machine, I will try to make it work, but for now unless someone fix this bug I cannot help you. If you really want to try the whisper model you can install tools like pip and git. Then go to README.md and step by step, copy all commands to command prompt (Command Prompt is installed on windows machine, you can search for it)

**Comment by StarDrop9** [comment]
failed)net::ERR_UPLOAD_FILE_CHANGED
Any idea how to correct this error on Post...?
running in vscode and windows 11 and virus protection by Trendmicro

**Comment by sonkite225** [comment]
> Greetings, could you please tell me if there are plans to make a full-fledged GUI that you can run as a local program?

there is already one called Buzz
https://github.com/chidiwilliams/buzz
:)

**Comment by ghost** [comment]
hi, thankyou for this web interface, i am trying to make it work on localnetwork and not only on localhost, i see uvicorn is running on 127.0.0.1 in run.py , but if i change the ip to my machine ip, it does not change.

Thank you in advance

**Comment by Kabanosk** [comment]
I don't know how to host a website on your local machine. Sory 😕

**Comment by iteachmachines** [comment]
I just tested it.When I upload a mp3 file it says internal server error.Any idea why?
I tried to run it locally.

**Comment by Kabanosk** [comment]
Hi @iteachmachines ! Do you use the run.py file or windows_run.bat to start it?

**Comment by iteachmachines** [comment]
Hello @Kabanosk yes I tried running both through run.py file and through windows_run.bat.

**Comment by Kabanosk** [comment]
Where do you run them? In cmd or powershell, or just click on this file?

**Comment by Kabanosk** [comment]
Where do you run them @iteachmachines ? In cmd or powershell, or just click on those files?

**Comment by iteachmachines** [comment]
VS code terminal.Created a virutalenv, installed the necessary dependencies and then run it.

**Comment by Kabanosk** [comment]
When you run it in vscode terminal and get the internal server error, you should have error message in this terminal. Can you copy and paste the error here? @iteachmachines
