### ISSUE TITLE
ImportError: cannot import name 'whisper' from 'whisper'

### ISSUE THREAD

**Issue by redhumus** [Kabanosk/website_for_whisper#5]
Thanks for doing this project.  I'm looking for use website in a  network server, but when I try to run main.py it says ti cannot import whisper module.
I tried this in my PC and found that mispell error causing this in main.py:

```
import whisper from whisper
```

I you chance second whisper to Capital letter ti works:

```
import whisper from Whisper
```

**Comment by Kabanosk** [comment]
Hi! Thanks for saying that. Did you also download the whisper repo? It is submodule so it isn't download with my repo. I want to change it to pip package in this week. I don't know why whisper with capital letter works, but thanks for letting me know!

**Comment by Kabanosk** [comment]
I added this step to README. Thanks for letting me know about it

**Comment by Kabanosk** [comment]
I change whisper submodule to pip package. Can you try clone it again and tell me if everything works now?
