### ISSUE TITLE
Run Pyhton on windows using windows_run.bat

### ISSUE THREAD

**Issue by nivb52** [Kabanosk/website_for_whisper#7]
**Describe the bug**
The command in windows to run python is ```python``` not ```python3```
When using Installing python from the python.org 

**OS (please complete the following information):**
Windows

**Additional context**
At file: windows_run.bat
Line 3

**Comment by Kabanosk** [comment]
Hi! Thanks for letting me know. I will change it in a minute. Can you try this script after changes?
